# Generated by Django 2.2.4 on 2020-04-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200420_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordred',
            new_name='ordered',
        ),
    ]
