# Generated by Django 2.2.4 on 2020-04-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='county',
            field=models.CharField(max_length=30),
        ),
    ]
