# Generated by Django 2.2.4 on 2020-04-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_item_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='field',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
