# Generated by Django 2.2.4 on 2020-04-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200422_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='adress',
            new_name='address',
        ),
    ]
